; Code generated by editorgen; DO NOT EDIT.
;
; tree-sitter highlight queries for masterbelt, projected from the category
; table (the language server's semantic token types) to helix's capture names.
; The query structure is shared across editors; only the capture names differ.

(doc_comment) @comment.block.documentation
[(line_comment) (block_comment)] @comment

[(integer) (datetime) (duration)] @constant.numeric.integer
(escape_sequence) @constant.character.escape
(string) @string

[
  "assert"
  "async"
  "await"
  "builtin"
  "const"
  "else"
  "enum"
  "extern"
  "false"
  "fn"
  "for"
  "from"
  "if"
  "impl"
  "in"
  "interface"
  "io"
  "let"
  "match"
  "nondet"
  "null"
  "of"
  "pub"
  "return"
  "self"
  "switch"
  "true"
  "type"
  "use"
  "where"
  "get"
  "set"
  "static"
] @keyword

[
  ":"
  "="
  "->"
  "?"
  ".."
  "..."
] @operator

(const_decl name: (identifier) @variable)
(let_stmt name: (identifier) @variable)
(type_decl name: (identifier) @type)
(enum_decl name: (identifier) @type)
(interface_decl name: (identifier) @type)
(master_decl name: (identifier) @type)
(generic_param name: (identifier) @type)
(func_decl name: (identifier) @function)
(method_decl name: (identifier) @function.method)
(interface_member name: (identifier) @function.method)
(param name: (identifier) @variable.parameter)
(field name: (identifier) @variable.other.member)
(record_field name: (identifier) @variable.other.member)
(master_primary (identifier) @variable.other.member)
(enum_member name: (identifier) @constant)
(use_decl (identifier) @namespace)
(modifier) @keyword
(master_keyword) @keyword

(type_name (identifier) @type)
(record_literal type: (identifier) @type)
(value_ref (identifier) @variable)
(member_expr member: (identifier) @variable.other.member)

(call_expr callee: (value_ref (identifier) @function))
(call_expr callee: (member_expr member: (identifier) @function.method))
