// Code generated by editorgen from pkg/source/token; DO NOT EDIT.
//
// The lexical layer of the masterbelt tree-sitter grammar: the keyword table,
// operator spellings, comment markers, and literal regexes the lexer commits
// on — the same lexer truth the TextMate grammar is generated from. The
// hand-written grammar.js requires this module and builds the structural rules
// on top, so the second parser's lexer cannot drift from the real one.

module.exports = {
  // The language identity shared across every target (C-2 §6).
  name: "masterbelt",

  // The identifier / word rule. Declared as the grammar's `word` token, so
  // the keywords below lex as keywords rather than as identifiers.
  identifier: /[A-Za-z_][A-Za-z0-9_]*/,

  // Reserved words, by spelling; referenced by name from grammar.js (kw.const).
  kw: {
    "assert": "assert",
    "async": "async",
    "await": "await",
    "builtin": "builtin",
    "const": "const",
    "else": "else",
    "enum": "enum",
    "extern": "extern",
    "false": "false",
    "fn": "fn",
    "for": "for",
    "from": "from",
    "if": "if",
    "impl": "impl",
    "in": "in",
    "interface": "interface",
    "io": "io",
    "let": "let",
    "match": "match",
    "nondet": "nondet",
    "null": "null",
    "of": "of",
    "pub": "pub",
    "return": "return",
    "self": "self",
    "switch": "switch",
    "true": "true",
    "type": "type",
    "use": "use",
    "where": "where",
  },

  // Fixed operator and punctuation spellings, by token kind name (op.Arrow).
  op: {
    "Colon": ":",
    "Question": "?",
    "Assign": "=",
    "Plus": "+",
    "Minus": "-",
    "Star": "*",
    "Slash": "/",
    "Percent": "%",
    "EqEq": "==",
    "BangEq": "!=",
    "Lt": "<",
    "LtEq": "<=",
    "Gt": ">",
    "GtEq": ">=",
    "AmpAmp": "&&",
    "PipePipe": "||",
    "Bang": "!",
    "LParen": "(",
    "RParen": ")",
    "LBrace": "{",
    "RBrace": "}",
    "LBracket": "[",
    "RBracket": "]",
    "Comma": ",",
    "Dot": ".",
    "DotDot": "..",
    "DotDotDot": "...",
    "Pipe": "|",
    "Arrow": "->",
  },

  // Literal token regexes. grammar.js tries datetime and duration before a
  // bare integer; tree-sitter's longest-match then makes "3w4d" a duration
  // and "100" an integer.
  integer: /0[bB][01]+|0[oO][0-7]+|0[xX][0-9A-Fa-f]+|[0-9]+/,
  datetime: /D[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{3})?(Z|[+-][0-9]{2}:[0-9]{2})/,
  duration: /([0-9]+(ms|w|d|h|m|s))+/,

  // A string escape sequence; grammar.js builds the surrounding string rule.
  escape: /\\(u\{[0-9A-Fa-f]{1,6}\}|[nrt0\\"])/,

  // Comment markers; grammar.js builds the trivia (extras) rules from them.
  comment: {
    line: "//",
    doc: "///",
    blockOpen: "/*",
    blockClose: "*/",
  },
};
