; Code generated by editorgen; DO NOT EDIT.
;
; tree-sitter highlight queries for masterbelt, projected from the category
; table (the language server's semantic token types) to nvim-treesitter (the default)'s capture names.
; The query structure is shared across editors; only the capture names differ.

(doc_comment) @comment.documentation
[(line_comment) (block_comment)] @comment

[(integer) (datetime) (duration)] @number
(escape_sequence) @string.escape
(string) @string

[
  "assert"
  "async"
  "await"
  "builtin"
  "const"
  "else"
  "enum"
  "extern"
  "false"
  "fn"
  "for"
  "from"
  "if"
  "impl"
  "in"
  "interface"
  "io"
  "let"
  "match"
  "nondet"
  "null"
  "of"
  "pub"
  "return"
  "self"
  "switch"
  "true"
  "type"
  "use"
  "where"
  "get"
  "set"
  "static"
] @keyword

[
  ":"
  "="
  "->"
  "?"
  ".."
  "..."
] @operator

(const_decl name: (identifier) @variable)
(let_stmt name: (identifier) @variable)
(type_decl name: (identifier) @type)
(enum_decl name: (identifier) @type)
(interface_decl name: (identifier) @type)
(master_decl name: (identifier) @type)
(generic_param name: (identifier) @type)
(func_decl name: (identifier) @function)
(method_decl name: (identifier) @function.method)
(interface_member name: (identifier) @function.method)
(param name: (identifier) @variable.parameter)
(field name: (identifier) @property)
(record_field name: (identifier) @property)
(master_primary (identifier) @property)
(enum_member name: (identifier) @constant)
(use_decl (identifier) @module)
(modifier) @keyword
(master_keyword) @keyword

(type_name (identifier) @type)
(record_literal type: (identifier) @type)
(value_ref (identifier) @variable)
(member_expr member: (identifier) @property)
(member_expr member: ["assert" "async" "await" "builtin" "const" "else" "enum" "extern" "false" "fn" "for" "from" "if" "impl" "in" "interface" "io" "let" "match" "nondet" "null" "of" "pub" "return" "self" "switch" "true" "type" "use" "where"] @property)
(type_name ["assert" "async" "await" "builtin" "const" "else" "enum" "extern" "false" "fn" "for" "from" "if" "impl" "in" "interface" "io" "let" "match" "nondet" "null" "of" "pub" "return" "self" "switch" "true" "type" "use" "where"] @type)
(field name: ["assert" "async" "await" "builtin" "const" "else" "enum" "extern" "false" "fn" "for" "from" "if" "impl" "in" "interface" "io" "let" "match" "nondet" "null" "of" "pub" "return" "self" "switch" "true" "type" "use" "where"] @property)
(record_field name: ["assert" "async" "await" "builtin" "const" "else" "enum" "extern" "false" "fn" "for" "from" "if" "impl" "in" "interface" "io" "let" "match" "nondet" "null" "of" "pub" "return" "self" "switch" "true" "type" "use" "where"] @property)
(param name: ["assert" "async" "await" "builtin" "const" "else" "enum" "extern" "false" "fn" "for" "from" "if" "impl" "in" "interface" "io" "let" "match" "nondet" "null" "of" "pub" "return" "self" "switch" "true" "type" "use" "where"] @variable.parameter)

(call_expr callee: (value_ref (identifier) @function))
(call_expr callee: (member_expr member: (identifier) @function.method))
(call_expr callee: (member_expr member: ["assert" "async" "await" "builtin" "const" "else" "enum" "extern" "false" "fn" "for" "from" "if" "impl" "in" "interface" "io" "let" "match" "nondet" "null" "of" "pub" "return" "self" "switch" "true" "type" "use" "where"] @function.method))
